---
- name: Configure bindip
  template:
    src=etc/elasticsearch/elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    mode=644
  notify: restart elasticsearch

- name: Configure start options
  template:
    src=etc/default/elasticsearch.j2
    dest=/etc/default/elasticsearch
    owner=root
    mode=644
  notify: restart elasticsearch
