---
- name: Install packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=1800
    install_recommends=no
  with_items:
    - elasticsearch

- name: Ensure elasticsearch is running
  service:
    name=elasticsearch
    state=started
    enabled=yes
  when: ansible_service_mgr == 'service'

- name: Activate elasticsearch systemd service
  systemd:
    name=elasticsearch
    daemon_reload=yes
    enabled=yes
    state=started
  when: ansible_service_mgr == 'systemd'
