---
- name: Get installed elastic plugins list
  command: "bin/plugin list chdir=/usr/share/elasticsearch"
  changed_when: false
  register: elastic_installed_plugins

- name: Install elastic plugins
  command: "bin/plugin install {{item.path}} chdir=/usr/share/elasticsearch"
  with_items: "{{elastic_install_plugins}}"
  when: "'- {{item.name}}' not in elastic_installed_plugins.stdout"
