---
- name: Add Elastic APT key
  apt_key: data="{{ elasticsearch_key }}"

- name: Add Elasticsearch repository
  apt_repository:
    repo="{{ item }}"
  with_items:
  - "deb http://packages.elasticsearch.org/logstash/5.x/apt stable main"

- name: Install packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=1800
    install_recommends=no
  with_items:
  - logstash

- name: Ensure logstash is running
  service:
    name=logstash
    state=started
    enabled=yes
