---
- name: Install packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=1800
  with_items:
  - kibana

- name: Ensure kibana is running
  service:
    name=kibana
    state=started
    enabled=yes
  when: ansible_service_mgr == 'service'

- name: Activate kibana systemd service
  systemd:
    name=kibana
    daemon_reload=yes
    enabled=yes
    state=started
  when: ansible_service_mgr == 'systemd'
