---
- name: Add Elastic APT key
  apt_key: data="{{ elasticsearch_key }}"

- name: Add Elasticsearch repository
  apt_repository:
    repo="{{ item }}"
  with_items:
  - "deb http://packages.elasticsearch.org/kibana/{{ kibana_version }}/debian stable main"

- name: Install packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=1800
    install_recommends=no
  with_items:
  - kibana

- name: Ensure Kibana is running
  service:
    name=kibana
    state=started
    enabled=yes

- name: Copy htpwds credentials
  template:
    src=etc/kibana/kibana-pwds.j2
    dest=/opt/kibana/config/kibana-pwds
    owner=root
    group=nginx
    mode=0640
  notify:
  - reload nginx
