---

- name: Create cert directory
  file:
    path="{{ cert_dir }}"
    state=directory
    owner=root
    group=root
    mode=0755

- name: Populate cert chain
  copy:
    dest="{{ cert_dir }}/{{ cert_chain_file }}"
    content="{{ cert_chain_data }}"
    owner=root
    group=root
    mode=0644

- name: Populate cert key
  copy:
    dest="{{ cert_dir }}/{{ cert_key_file }}"
    content="{{ cert_key_data }}"
    owner=root
    group=root
    mode=0400
